# Generated by Django 3.0.4 on 2020-03-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=100)),
                ('group_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Patrolmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Patrol')),
            ],
        ),
    ]
