# Generated by Django 3.0.4 on 2020-03-22 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_patrol_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='A csapatszám nem tartalmazhat nem numerikus értéket!', regex='^[0-9]*$')]),
        ),
    ]
