# Generated by Django 3.0.4 on 2020-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0003_auto_20200322_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(),
        ),
    ]
