# Generated by Django 3.0.4 on 2020-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0004_auto_20200322_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolmember',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
