# Generated by Django 3.0.4 on 2020-03-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0006_auto_20200326_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patrolmember',
            unique_together={('nickname', 'patrol')},
        ),
    ]
