# Generated by Django 3.0.4 on 2020-03-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0004_auto_20200326_1027'),
        ('ors', '0007_auto_20200326_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kihivasok.Challenge')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Patrol')),
            ],
        ),
    ]
