# Generated by Django 3.0.4 on 2020-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0004_auto_20200326_1027'),
        ('ors', '0008_patrolchallenge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patrolchallenge',
            unique_together={('patrol', 'challenge')},
        ),
    ]
