# Generated by Django 3.0.4 on 2020-03-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ors', '0011_auto_20200327_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolChellengeCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Patrol')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
