# Generated by Django 3.0.4 on 2020-03-30 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ors', '0012_patrolchellengecart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatrolChellengeCart',
            new_name='PatrolChallengeCart',
        ),
    ]
