# Generated by Django 3.0.4 on 2020-03-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0013_auto_20200330_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatrolChallengeCart',
        ),
    ]
