# Generated by Django 3.0.4 on 2020-03-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0014_delete_patrolchallengecart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolmemberChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'None'), ('A', 'Assigned'), ('F', 'Finished')], max_length=1)),
                ('times', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.PatrolChallenge')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Patrolmember')),
            ],
            options={
                'unique_together': {('nickname', 'challenge')},
            },
        ),
    ]
