# Generated by Django 3.0.4 on 2020-03-31 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0005_challenge_add_to_patrol'),
        ('ors', '0015_patrolmemberchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolmemberchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kihivasok.Challenge'),
        ),
    ]
