# Generated by Django 3.0.4 on 2020-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0016_auto_20200331_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
