# Generated by Django 3.0.4 on 2020-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0017_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
