# Generated by Django 3.0.4 on 2020-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0018_auto_20200407_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
