# Generated by Django 3.0.4 on 2020-04-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patrol',
            field=models.CharField(default='Alma', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_num',
            field=models.IntegerField(default=1),
        ),
    ]
