# Generated by Django 3.0.4 on 2020-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200407_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
