# Generated by Django 3.0.4 on 2020-04-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0019_auto_20200407_1145'),
        ('accounts', '0006_auto_20200407_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ors.Group'),
        ),
    ]
