# Generated by Django 3.0.4 on 2020-04-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0019_auto_20200407_1145'),
        ('accounts', '0008_auto_20200407_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(default='0. cscs', on_delete=django.db.models.deletion.CASCADE, to='ors.Group'),
        ),
    ]
