# Generated by Django 3.0.4 on 2020-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0002_auto_20200322_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actual', models.BooleanField()),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
