# Generated by Django 3.0.4 on 2020-03-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0003_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsPost',
        ),
    ]
