# Generated by Django 3.0.4 on 2020-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0004_auto_20200326_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='add_to_patrol',
            field=models.BooleanField(default=True),
        ),
    ]
