# Generated by Django 3.0.4 on 2020-04-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200407_1008'),
        ('kihivasok', '0006_challenge_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
