# Generated by Django 3.0.4 on 2020-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0007_auto_20200407_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_by',
        ),
    ]
