# Generated by Django 3.0.4 on 2020-04-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0008_remove_challenge_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
