# Generated by Django 3.0.4 on 2020-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kihivasok', '0009_challenge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
